### ISSUE TITLE
add YouTube links

### ISSUE THREAD

**Issue by lizkirk82** [jameskirk84/lizard-website#15]
I've embedded a Youtube video - is it possible to :
-add a hyerlink to the work 'youtube' where is says 'please visit my youtube channel' or the whole sentence?
-add a youtube icon on my contact me page also oryou tube icon on service page?

**Comment by jameskirk36** [comment]
Lets have a discussion about this because i'd like to understand more about how you want to use videos on your website.  Depending on what you want to do, there will likely be a variety of options to discuss.  I'll msg on whatsapp to arrange chat

**Comment by jameskirk36** [comment]
added youtube link to contact page.  You can add a link in the text yourself when you're editing the page.  There should be a link button in the text editor toolbar
