### ISSUE TITLE
removal of video on services page

### ISSUE THREAD

**Issue by lizkirk82** [jameskirk84/lizard-website#17]
so the original video of alice doing press ups i decided to remove and use the embedded youtube video which works much better i think, 

I then tried to delete the video element of the page but it would let me leave the boxes blank
I then attempted to add a picture to the video box iinstead, which displays on my phone but not on my  laptop when published...

so, i think now maybe worth removing that section from the website if that's possible , 

Ta very much lad! :D

**Comment by jameskirk36** [comment]
I've removed the video elements from the admin page now
